// Bloque 1: Bases de datos de origen (organizaciones nacionales) INPUTs

Table Data_base_INE {
  codigo_postal int [primary key]
  gamma float [note: 'Referencia oficial para viviendas físicas']
}

Table Data_base_CNP {
  dni_nie_nif varchar [primary key, note: 'Eje de identidad (DNI, NIE, NIF)']
  edad int
}

Table Data_base_Hacienda {
  dni_nie_nif varchar [primary key]
  renta_mensual float [note: 'Si > 0, entrada automática por actividad económica']
}

Table Data_base_Ministerio_Vivienda {
  ref_catastral varchar [primary key]
  codigo_postal int [ref: > Data_base_INE.codigo_postal]
}

Table Data_base_Padron {
  dni_nie_nif varchar [primary key]
  ref_catastral varchar [ref: > Data_base_Ministerio_Vivienda.ref_catastral]
}

Table Data_base_Asistencia_Social {
  dni_nie_nif varchar [primary key]
  municipio_asistencia varchar
  phi_social float [note: 'Vulnerabilidad definida por el trabajador social']
  gamma_local float [note: 'Coste de vida local definido por el municipio']
}


// Bloque 2: Transformación (Lógica EFRD - ocurre en la RAM)

Table Habitabilidad_Real {
  id_interno int [primary key] 
  dni_nie_nif varchar [ref: > Data_base_CNP.dni_nie_nif]
  ref_catastral varchar [note: 'Padrón (Física) | Hacienda/Asistencia (Virtual)']
  es_residencia_habitual boolean 
  
  Note: 'Esta tabla es Auxiliar. Resuelve la identidad y asigna el "techo" (Físico o Virtual). No existe como archivo.'
}

// Bloque 3: Salida final (es una analogía al .csv)

Table Base_Datos_FINAL {
  ref_catastral varchar [primary key, note: 'ID Vivienda o VIRTUAL_DNI']
  tipo_unidad varchar // fisica | virtual
  es_habitual boolean
  lista_inquilinos text // [(ID, renta, phi), ...]
  gamma float [note: 'INE (si física) | Asistencia_Social (si virtual)']
  
  Note: '\Phi en lista_inquilinos prioriza: 1. Edad, 2. Asistencia Social, 3. Hacienda'
}


// Relaciones del sistema. 

// Vinculación de Ciudadanos con Porteros
Ref: Data_base_Padron.dni_nie_nif > Data_base_CNP.dni_nie_nif
Ref: Data_base_Hacienda.dni_nie_nif > Data_base_CNP.dni_nie_nif
Ref: Data_base_Asistencia_Social.dni_nie_nif > Data_base_CNP.dni_nie_nif

// Las 3 Vías de Entrada al Motor de Habitabilidad
Ref: Habitabilidad_Real.dni_nie_nif > Data_base_Padron.dni_nie_nif
Ref: Habitabilidad_Real.dni_nie_nif > Data_base_Asistencia_Social.dni_nie_nif
Ref: Habitabilidad_Real.dni_nie_nif > Data_base_Hacienda.dni_nie_nif

// Salida de Datos hacia el Resultado Final
Ref: Base_Datos_FINAL.ref_catastral < Habitabilidad_Real.ref_catastral

// Atribución Geográfica y Económica
Ref: Base_Datos_FINAL.ref_catastral > Data_base_Ministerio_Vivienda.ref_catastral
Ref: Data_base_INE.gamma - Base_Datos_FINAL.gamma
Ref: Data_base_Asistencia_Social.gamma_local - Base_Datos_FINAL.gamma